# Template Configuration file for local development. You should make a copy of this file
# and place it in the same folder. The copy of this file should be named config.yml. config.yml is
# ignored by git and you can change that file without accidentally committing any changes to the
# configuration ( see git ignore file in the root of the project ).

# Your database connection configuration used when database
# migrations are executed.
# The configuration should be identical for the normal database
# configuration. You should only provide connection information
# to a a Postgres database, because it's the only one supported.
liquibase-database:
  user: postgres
  password: mysecretpassword
  url: jdbc:postgresql://localhost:5432/barrier

database:
  user: application_user
  password: pass
  url: jdbc:postgresql://localhost:5432/barrier

# Logging defines how the application will log. During development logs will be sent to standard out.
# Threshold for log level can be configured here.
logging:
  additivity:
    com.fortnox.reactivewizard.ReactiveWizardServer: false
    se.fortnox.reactivewizard.jaxrs.JaxRsResource: false
  levels:
    com.fortnox.reactivewizard.ReactiveWizardServer: INFO
    se.fortnox.reactivewizard.jaxrs.JaxRsResource: INFO
  appenders:
    stdout:
      threshold: INFO
